{% set name = "pynmea2" %}
{% set version = "1.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynmea2-{{ version }}.tar.gz
  sha256: 1daa79b93279f887d1c235e5cc5c79e32644564138ce46989ab0f4a2fc970d7c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pynmea2
    - pynmea2.types
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Knio/pynmea2
  summary: Python library for the NMEA 0183 protcol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
